tap "homebrew/bundle"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
# Deprecated; must install manually
# brew "fasd"
brew "fzf"
brew "jump"
brew "neovim"
brew "ripgrep"
brew "wget"
brew "tmux"
cask "font-hack-nerd-font"
cask "finicky"
